-- reload
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local HOME = os.getenv("HOME")

hl.bind("CTRL + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload && shikanectl reload && $(pkill waybar && waybar)"))

-- Print
hl.bind("SUPER + A", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("hyprshot -m region"))
--bind = SHIFT, Print,exec, distrobox-enter -n Arch -- hyprshot -m output -o $HOME/Pictures/Screenshots

local LockName = "hyprlock"
local LockCmd = "pidof hyprlock || hyprlock"
-- Lid
-- bindl= , switch:on:Lid Switch, exec, $HOME/.local/bin/lid-close
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd(HOME .. "/.local/bin/lid-open"), { locked = true })

-- Launchers
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("kitty bash"))
--bind = SUPER, W, exec, flatpak run org.mozilla.firefox
--bind = SUPER, E, exec, nautilus
hl.bind("SUPER + D", hl.dsp.exec_cmd("wofi --normal-window --show drun"))
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("wofi --normal-window --show run"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("networkmanager_dmenu"))

-- Plugins
-- hl.bind("SUPER + SHIFT + T", hl.dsp.darkwindow_shadeactive("invert"))

-- Bindings
hl.bind("CTRL + ALT + Delete", hl.dsp.exit())
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + G", hl.dsp.group.toggle())
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind("SUPER + W", hl.dsp.layout("togglesplit"))

-- Special workspace
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratchpad" }))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("scratchpad"))

-- Move focus with mainMod + arrow keys
hl.bind("SUPER + k", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + j", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + l", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + h", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + left", hl.dsp.group.next())
hl.bind("SUPER + right", hl.dsp.group.prev())

-- group related
hl.bind("CTRL + SHIFT + SUPER + h", hl.dsp.group.move_window("l"))
hl.bind("CTRL + SHIFT + SUPER + j", hl.dsp.group.move_window("d"))
hl.bind("CTRL + SHIFT + SUPER + k", hl.dsp.group.move_window("u"))
hl.bind("CTRL + SHIFT + SUPER + l", hl.dsp.group.move_window("r"))

-- Switch workspaces with mainMod + [0-9]
-- hl.bind("SUPER + left", hl.dsp.focus({ workspace = "e-1" }))
-- hl.bind("SUPER + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))

-- Multi-monitor
hl.bind("CTRL + SUPER + h", hl.dsp.workspace.move({ monitor = "l" }))
hl.bind("CTRL + SUPER + j", hl.dsp.workspace.move({ monitor = "d" }))
hl.bind("CTRL + SUPER + k", hl.dsp.workspace.move({ monitor = "u" }))
hl.bind("CTRL + SUPER + l", hl.dsp.workspace.move({ monitor = "r" }))

-- will switch to a submap called resize
hl.bind("SUPER + R", hl.dsp.submap("resize"))

-- will start a submap called "resize"
hl.define_submap("resize", function()
    -- sets repeatable binds for resizing the active window
    hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

    -- use reset to go back to the global submap
    hl.bind("escape", hl.dsp.submap("reset"))
    -- will reset the submap, meaning end the current one and return to the global one
    -- (end of submap block)
end)

hl.bind("SUPER + X", hl.dsp.submap("system"), { locked = true })

-- will start a submap called "system" and reset after dispatch
hl.define_submap("system", "reset", function()
    hl.bind("l", hl.dsp.exec_cmd(LockCmd .. " && sleep 1"))
    hl.bind("e", hl.dsp.exit(), { locked = true })
    hl.bind("SUPER + s", hl.dsp.exec_cmd(LockCmd .. " && sleep 1 && systemctl suspend"), { locked = true })
    hl.bind("h", hl.dsp.exec_cmd(LockCmd .. " && sleep 1 && systemctl hibernate"), { locked = true })
    hl.bind("r", hl.dsp.exec_cmd("systemctl reboot"), { locked = true })
    hl.bind("s", hl.dsp.exec_cmd("systemctl poweroff -i"), { locked = true })
    -- (end of submap block)
end)
-- Move active window to workspace
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + j", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

-- Laptop
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(HOME .. "/.local/bin/volume up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(HOME .. "/.local/bin/volume down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(HOME .. "/.local/bin/volume mute_toggle"), { locked = true })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
