-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/envs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("envs")
-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/settings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("settings")
-- Source: ~/.config/hypr/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("rules")
-- Source: ~/.config/hypr/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binds")
-- Source: ~/.config/hypr/theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("theme")
-- Source: ~/.config/hypr/startup.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("startup")
-- Source: ~/.config/hypr/plugins.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("plugins")
