-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — plugin section 'darkwindow'. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  shader[smartInvert] { ... }
]]

