-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(Rofi)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.Calculator)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.Nautilus)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(eww)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(blueberry.py)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.Settings)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.design.Palette)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Color Picker)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Network)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-gnome)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(transmission-gtk)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(nm-openconnect-auth-dialog)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.kde.kdeconnect.app)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Xpra)$",
        title = ".*autopilot.*",
    },
    float = true,
    move = "cursor_x cursor_y",
})

hl.window_rule({
    match = {
        class = "^(me.kavishdevar.librepods)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Xpra)$",
        title = ".*JidePopup.*",
    },
    float = true,
    no_initial_focus = true,
    size = "302 91",
    move = "monitor_w-302 44",
})

hl.window_rule({
    match = {
        class = "^(xfreerdp)$",
    },
    float = false,
})

hl.window_rule({
    match = {
        class = "(wofi)",
    },
    stay_focused = true,
    border_size = 0,
})

hl.window_rule({
    match = {
        class = "(kitty)",
        title = "(scratchpad)",
    },
    float = true,
    center = true,
    size = "(monitor_w*0.5) (monitor_h*0.5)",
})

local office_apps = "^(Microsoft (Word|Excel|PowerPoint|Publisher|Powershell|Visual Studio|Explorer))|Command Prompt$"
hl.window_rule({
    match = {
        class = office_apps,
    },
    suppress_event = "maximize fullscreen",
})

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
hl.window_rule({ match = { float = false, workspace = "w[tv1]" }, border_size = 0 })
hl.window_rule({ match = { float = false, workspace = "w[tv1]" }, rounding = 0 })
hl.window_rule({ match = { float = false, workspace = "f[1]" }, border_size = 0 })
hl.window_rule({ match = { float = false, workspace = "f[1]" }, rounding = 0 })
