-- exec-once=dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP #&& systemctl --user start hyprland-session.target

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- exec-once = wlsunset
-- exec-once = $HOME/.config/eww/scripts/init
--exec-once = swayidle -w
--exec-once = sway-audio-idle-inhibit
--exec-once = ~/.profile
--exec-once = flatpak run com.transmissionbt.Transmission
--exec-once = hyprctl setcursor Qogir 24
--blurls "eww_powermenu"

hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("shikane")
    hl.exec_cmd("kitty --title scratchpad", { workspace = "special:scratchpad silent" })
    hl.exec_cmd("keepassxc", { workspace = "special:keepass silent" })
    hl.exec_cmd("xrdb -load ~/.Xresources")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("mako")
    hl.exec_cmd("hyprpm reload")
end)

