--monitor=eDP-1,addreserved,0,0,-16,0

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 5,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})
hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border = "rgba(51a4e780)",
            inactive_border = "rgb(2a2a2a)",
        },
    },
    decoration = {
        rounding = 11,
        blur = {
            enabled = false,
            -- size = 2
            -- passes = 2
        },
        shadow = {
            enabled = false,
        },
        -- blur_new_optimizations = true
        -- shadow_range = 8
        -- shadow_render_power = 2
        -- col.shadow = rgba(00000044)
        dim_inactive = false,
    },
    animations = {
        enabled = true,
    },
})

