[manager]
ratio         = [ 1, 3, 4 ]
sort_by       = "modified"
sort_reverse  = true

[preview]
max_width     = 1080
max_height    = 1920
[opener]
edit = [
	{ run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
