#!/bin/bash


function mute_state {

    STATE=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    echo $STATE
}

function get_volume {
    VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | grep Volume | awk '{print $5}' | tr -d %)
    echo $VOLUME
}

function get {
    VOLUME=$(get_volume)
    if [[ $(mute_state) == 'yes' ]]; then ICON='󰝟'
    elif [[   $VOLUME -ge 66 ]]; then ICON='󰕾'
    elif [[ $VOLUME -ge 33 ]]; then ICON='󰖀'
    elif [[ $VOLUME -ge 1  ]]; then ICON='󰕿'
    else ICON='󰝟'
    fi
    echo '{"volume": "'$VOLUME'", "icon": "'$ICON'", "muted": "'$(mute_state)'"}'
}


echo $(get)

pactl subscribe | rg --line-buffered "on sink" | while read -r _; do
  echo $(get)
done
