#! /bin/bash
function percent {
  echo $(cat /sys/class/power_supply/BAT1/capacity)
}

function status {
  echo $(cat /sys/class/power_supply/BAT1/status)
}

function icon {
  echo ''
}

function get {
  echo "{\"percent\":$(percent),\"state\":\"$(status)\"}"
}

if [[ $1 == 'get' ]]; then get; fi
